# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'
source 'https://github.com/CocoaPods/Specs.git'
target 'CityAdventure' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
   # Network
    pod 'Alamofire', '~> 4.0'
    pod 'AlamofireObjectMapper', '~> 5.0'
    
    # Layout
    pod 'SnapKit', '~> 4.0.0'
    

    # ImageCache
    pod 'Kingfisher', '~> 4.0'


    # Toast
    pod 'Toaster'

    # GIF
    pod 'SwiftGifOrigin', '~> 1.6.1'
    
    # Modeling 
    pod 'ObjectMapper', '~> 3.1'
    
    # DataBase
    pod 'GRDB.swift'
  # Pods for CityAdventure
end
